###################################################################################
# This is oly's configuration file.                                               #
# Please edit the following values.                                               #
#                                                                                 #
# A list of all possible configuration options and their defaults can be found at #
# https://github.com/anonymousgrasshopper/oly/blob/main/src/config.cpp#L50-#L84   #
###################################################################################

# The author's name in the LaTeX preview
author: Leonhard Euler

# The base path where solutions are stored
base_path: ~/Mathematics/Solutions

# The pdf viewer used for 'oly gen'
pdf_viewer: zathura

# wether to confirm deletion or not in 'oly rm'
confirm: true

# map contest names to other ones
abbreviations:
  Shortlist: ISL

# added right after \documentclass in the preview file
packages: '\usepackage[sexy,diagrams]{evan}
'
